### ISSUE TITLE
How to call win32 api?

### ISSUE THREAD

**Issue by dosgo** [tinysun212/swift-cygwin#1]
Hello, how to call win32 api?
There is no dlopen method? If you can dynamically load the dll, you can call all the win32 api.

**Comment by tinysun212** [comment]
This link (https://swiftforwindows.codeplex.com/workitem/1) will be helpful for calling the Win32 API.

**Comment by dosgo** [comment]
Thank you, will also use the C standard library yet?

**Comment by dosgo** [comment]
Seemingly not Darwin module.

**Comment by tinysun212** [comment]
[Cygwin port](https://github.com/tinysun212/swift-windows/releases/tag/swift-cygwin-20160521) can use `import Foundation` as well as `import SwiftGlibc`. But they are not perfect as Linux or Darwin.

**Comment by dosgo** [comment]
The latest cygwin is 2.5.2 and can not find Cygwin 2.5.1 64bit, swift.exe not running. . collapse.

**Comment by tinysun212** [comment]
I didn't know the newer Cygwin released. Up to dated Swift-cygwin will be downloadable this weekend.

**Comment by dosgo** [comment]
Thank you.

**Comment by dosgo** [comment]
![qq 20160711101057](https://cloud.githubusercontent.com/assets/9545458/16718159/e76bb33e-474f-11e6-9beb-b6813fa88ee4.png)

**Comment by dosgo** [comment]
I http://cygwin.mirror.constant.com/x86_64/release/gcc/libstdc%2B%2B6/libstdc%2B%2B6-5.3.0-5.tar.xz cygstdc ++ - 6.dll replacement, not being given a.

swiftc.exe Hello.swift not generated, Hello.exe

swift.exe Hello.swift
<Unknown>: 0: error: could not load the swift standard library

**Comment by tinysun212** [comment]
@dosgo, new version Swift for Cygwin is available [here](https://github.com/tinysun212/swift-windows/releases/tag/swift-cygwin-20160712). It is built under Cygwin 2.5.2.

**Comment by dosgo** [comment]
Hello, I am still the same error, you do not there? Am I missing some packages installed cygwin?

**Comment by dosgo** [comment]
![xx](https://cloud.githubusercontent.com/assets/9545458/16789600/ae7e4850-48e1-11e6-8573-80d762703a1f.png)

**Comment by dosgo** [comment]
I just installed cygwin in the default package.

**Comment by tinysun212** [comment]
Cygwin is an environment for POSIX. You should play in Cygwin64 terminal.

```
1. Open Cygwin64 Terminal
2. extract the archive
    tar zxvf swift-cygwin-20160712.tar.gz
3. Run Immediate mode
    cd swift/bin
    ./swift Hello.swift
4. Compile and Run
    cd swift/bin
    ./swiftc Hello.swift
    ./Hello
```

**Comment by tinysun212** [comment]
Can you create a file?

```
cp Hello.swift  Hello2.swift
ls -l  Hello*
```

**Comment by tinysun212** [comment]
And can you show me the output of this?

```
./swiftc Hello.swift -v
```

**Comment by dosgo** [comment]
![oo](https://cloud.githubusercontent.com/assets/9545458/16790048/2d51a55c-48e5-11e6-81c9-5a32463e9801.png)

**Comment by tinysun212** [comment]
Sorry, I don't know the message. Could you translate the message in English?

**Comment by dosgo** [comment]
./swiftc Hello.swift -v    No output.

**Comment by tinysun212** [comment]
What is the output of swiftc ?

**Comment by dosgo** [comment]
![jj](https://cloud.githubusercontent.com/assets/9545458/16790147/03a9c77e-48e6-11e6-9822-3cdf9b992bc6.png)

**Comment by tinysun212** [comment]
OK. 
How about  `swift Hello.swift` ?

**Comment by dosgo** [comment]
Same.  
![ii](https://cloud.githubusercontent.com/assets/9545458/16790215/84148386-48e6-11e6-8e45-73576a6a2902.png)

**Comment by dosgo** [comment]
![tt](https://cloud.githubusercontent.com/assets/9545458/16790233/a974f7c8-48e6-11e6-9703-b786105061ff.png)

**Comment by dosgo** [comment]
![cc](https://cloud.githubusercontent.com/assets/9545458/16790248/f04958ba-48e6-11e6-9f6d-8697fdc3bf7e.png)

**Comment by tinysun212** [comment]
Please

```
uname -a
```

**Comment by tinysun212** [comment]
Sorry, I'll continue this after lunch.

**Comment by dosgo** [comment]
![gg](https://cloud.githubusercontent.com/assets/9545458/16790358/d1b41e2a-48e7-11e6-9cd9-4591c5b3348d.png)

**Comment by dosgo** [comment]
May I know your contry?

**Comment by tinysun212** [comment]
The default packages are not sufficient. Two more packages are required.
1. Devel folder: clang (3.7.1-1) - C/C++ compiler frontend based on LLVM 
2. Lib folder: libicu57 (57.1-1) - IBM Internationalization Components for Unicode

I just tested under clean Windows 7 64bit with Cygwin 2.5.2, but your Cygwin version is 2.2.1.

**Comment by dosgo** [comment]
I may use the source mirros.163.com caused.
I try again, thank you.
![pp](https://cloud.githubusercontent.com/assets/9545458/16796379/074f6738-4915-11e6-8ec1-aee6e50cde8b.png)

**Comment by tinysun212** [comment]
Seoul, Korea. And you?

**Comment by dosgo** [comment]
Shanghai, China.
China visit cygwin source real slow.
So use mirros.163.com source.
The cause of all the problems.
very sorry.

**Comment by tinysun212** [comment]
Thanks for using my EXPERIMENTAL build.
Let me know if you have some problems related to the swift-cygwin.
Any troubleshoot will be helpful to other users and this project.

**Comment by dosgo** [comment]
![88](https://cloud.githubusercontent.com/assets/9545458/16808747/4c1846b0-4950-11e6-84cb-38eb29a81ff1.png)
![99](https://cloud.githubusercontent.com/assets/9545458/16808742/49389968-4950-11e6-896e-baf418fd7fed.png)

Missing package?

**Comment by tinysun212** [comment]
Try `Include` option first time, 

```
./swift Hello.swift -I /usr/include
```

It's a bug.

**Comment by dosgo** [comment]
![pp](https://cloud.githubusercontent.com/assets/9545458/16823451/fa708dee-4996-11e6-921d-dbf3f6ffeeaa.png)

**Comment by tinysun212** [comment]
How about compiler?

```
./swiftc Hello.swift -I /usr/include
```

**Comment by tinysun212** [comment]
I found that `Lib folder: libiconv-devel (1.14-3)` is needed for `TestFoundation.swift`. But `Hello.swift` was worked without `libiconv-devel`.
I think your installed packages are not equal to mine.
Do you have the file `/usr/include/complex.h`?

**Comment by dosgo** [comment]
I Hello.swift file to add the "import Foundation".

**Comment by tinysun212** [comment]
You can also check the development environment packages. [here](https://github.com/tinysun212/swift-windows/blob/upstream-with-windows/BUILD-CYGWIN-64.md)

**Comment by tinysun212** [comment]
If you imported `Foundation`, you should use `-lFoundation -lSwiftGlibc -I /usr/include` in this version.

**Comment by dosgo** [comment]
Well, use ./swift Hello.swift -Foundation -lSwiftGlibc -I / usr / include, thank you.

**Comment by tinysun212** [comment]
You may omit `-l` (link) option for `swift`, but `swiftc` will need it.

**Comment by tumasgiu** [comment]
Hello,
First of all, thanks for your hard work.

From what I’ve figured out, writing a Swift wrapper for Win32 seems doable, (and even WinRT [it seems](http://stackoverflow.com/questions/7436144/using-winrt-from-c)) and I’d like to contribute this to the community.

I’ve been toying with the latest cygwin pre-release but I haven’t successfully compiled more than the trivial “Hello World”.

I’ve read in the [link](https://swiftforwindows.codeplex.com/workitem/1) you mentioned that you could compile a program calling Win32 APIs by linking User32.lib but I lack the knowledge to do so.

I tried to run this in interpreter mode with`swift -I CWin32/ -I /usr/include/w32api/ -I /usr/include HelloW32.swift` under Cygwin 2.5.2 :

``` swift
import CWin32

enum MessageBox {
    struct Options: OptionSet {
        var rawValue: UInt32

        static let ok = Options(rawValue: 0)
        static let abortRetryIgnore = Options(rawValue: 0x2)
        static let iconExclamation = Options(rawValue: 0x30)
        static let cancelTryContinue = Options(rawValue: 0x6)
        static let help = Options(rawValue: 0x4000)
    }
}

func displayMessageBox(message: String, title: String = "Error", options: MessageBox.Options = .ok) {
    MessageBoxA(nil, message, title, options.rawValue)
}

func hello() {
    displayMessageBox(message: "Hello windows!", title: "Swift", options: [.iconExclamation, .help])
}

hello()
```

and here’s what i’ve got :

`LLVM ERROR: Program used external function '__imp_MessageBoxA' which could not be resolved!`

All my experiments are [there](https://github.com/tumasgiu/W32ExperimentStepOne)

**Comment by tinysun212** [comment]
I was impressed by your work.

Your code was compiled successfully and ran as expected - displaying popup message.

`swiftc -I CWin32/ -I /usr/include/w32api/ -I /usr/include HelloW32.swift`
`HelloW32.exe` 

As you described, it displays the llvm error message in the immediate mode.

I show a workaround right now, and I'll try to solve this problem later.

1) Add a macro to ignore the dll import directive in function prototypes

```
CWin32.h
#define DECLSPEC_IMPORT
#include <windows.h>
```

2) Remove module cache directory before you compile (every time)

```
rm -rf /tmp/org.llvm.clang.*
swift -I CWin32/ -I /usr/include/w32api/ -I /usr/include HelloW32.swift
```

I read your W32ExperimentStepOne in github. Could you check these for MSVC version?

  1)  installed VS2015
  2)  installed LLVM 3.8.x ( should be installed after VS2015 )
  3)  set PATH=%PATH%;c:/Program Files/Swift/bin;c:/Program Files/Swift/lib/swift/windows

**Comment by GunGraveKoga** [comment]
For MinGW-W64 version of Swift
CWin32.h

``` c
#include <stdlib.h>
#define DECLSPEC_IMPORT
#include <windows.h>
```

Build and execution success

**Comment by tumasgiu** [comment]
I tried on a fresh install of Windows 10 with MSVC Port (20160515), without the `-v` flag I have no output at all, and this is with it :

```
swiftc -I CWin32 -I "C:\Program Files (x86)\Windows Kits\8.1\Include\um" -v HelloW32.swift

Swift version 3.0-dev (LLVM f5d2d3e78d, Clang 296a35f432, Swift 5e4ad07574)
Target: x86_64-pc-windows-msvc
"c:\\Program Files\\Swift\\bin\\swiftc.exe" -frontend -c -primary-file HelloW32.swift -target x86_64-pc-windows-msvc -disable-objc-interop -I CWin32 -I "C:\\Program Files (x86)\\Windows Kits\\8.1\\Include\\um" -color-diagnostics -module-name HelloW32 -o "C:\\Users\\tumasgiu\\AppData\\Local\\Temp\\HelloW32-5c93ff.o"
```

There is no error, but no .exe is generated.
I tried to remove the caches in AppData\Local\Temp but it made no difference.

**Comment by tumasgiu** [comment]
Little update : I tried to go a bit further with [Step 2](https://github.com/tumasgiu/W32ExperimentStepTwo) and [3](https://github.com/tumasgiu/W32ExperimentStepThree) :

I should point out that I have very little experience with C and build systems, I’m learning as I go.

From what I understand, Win32 API use a different calling convention for its entry point and callback functions, and I have no idea how to generate an executable written in pure swift that would expose the correct ABI(?). 
Therefore the `main.c` hack.

As of now, [Experiment 2](https://github.com/tumasgiu/W32ExperimentStepTwo) compiles, but I’m stuck with Step 1 of [Experiment 3](https://github.com/tumasgiu/W32ExperimentStepThree) which fails with a segmentation fault due to a STATUS_ACCESS_VIOLATION exception.

**Comment by tinysun212** [comment]
It seems that there is a bug which generates the segment fault when compile is fail. I'll care this.

Anyway, you should avoid the `main.c` hack, because the method overrides some init procedure by swift.

For now, you can use `GetModuleHandle(NULL)` for `hInstance`, and `CommandLine` object for `hCmdLine`, and move the main.c code to Swift source.

```
    let hinst = GetModuleHandleA(nil)
    let dummy: UnsafeMutablePointer<CHAR>? = UnsafeMutablePointer.allocate(capacity: 1)
    //TODO: Use 'CommandLine' for 'lpCmdLine' (CommandLine is Process in older version)
    return Application.run(hInstance:hinst!, lpCmdLine:dummy!, nCmdShow:0)
```

BTW, You can build a module with shared library as follows.

```
export WORKDIR=/cygdrive/c/<Cygwin directory>

swiftc -force-single-frontend-invocation  -parse-as-library -emit-module -emit-module-path $WORKDIR/swift/lib/swift/cygwin/x86_64/Win32.swiftmodule -module-link-name Win32 -I /usr/include/ -I /usr/include/w32api/ -I CWin32/ -module-name "Win32" Win32/MessageBox.swift Win32/Application.swift -emit-library 

swiftc -I /usr/include/ -I /usr/include/w32api/ -I CWin32/  -L . SwiftW32App.swift 
```

`$WORKDIR/swift/lib/swift/cygwin/x86_64/Win32.swiftmodule`, `$WORKDIR/swift/lib/swift/cygwin/x86_64/Win32.swiftdoc`, `libWin32.dll`, `SwiftW32App.exe` will be generated.

**Comment by tumasgiu** [comment]
Noted, I will now know the error is most surely mine when I see this exception.
I followed your instructions and everything works fine. 
Now there will be many trials and errors on my end as I familiarise myself with all this.
Many, many thanks for helping me getting started.

**Comment by tumasgiu** [comment]
@GunGraveKoga Could you share the command used to compile it with MinGW ? 
When I tried I had many conflicts (previous declaration on the same line), it seems the headers are included twice.

@tinysun212 I had another go with the MSVC in immediate mode, the output might be of interest to you. It's [here](https://github.com/tumasgiu/W32ExperimentStepOne/blob/master/README.md).

It seems similar to an issue I had. When trying to compile a file with `CW_USEDEFAULT` in it, the compiler complains : `error: integer literal '2147483648' overflows when stored into signed 'Builtin.Int32'`

**Comment by GunGraveKoga** [comment]
@tumasgiu In CWin32.h header of your module include stdlib.h before windows.h

Compilation (MSYS2): swiftc -I./CWin32 -I/mingw64/x86_64-w64-mingw32/include ./HelloW32.swift -o hello.exe

JIT swift works fine too

**Comment by tinysun212** [comment]
@tumasgiu These days, I focus on porting of the Package Manger for Cygwin and then I will try to port the Foundation for MinGW. MSVC version will be cared after those. How about you concentrate on MinGW or Cygwin?

**Comment by tumasgiu** [comment]
Thank you. It does work as expected on MinGW.
It was a naive attempt to help by providing some feedback. If I can be of any assistance I'll be pleased.
Meanwhile I'll focus on the Cygwin version.

**Comment by tinysun212** [comment]
Now, I think we know how to call Win32 API in Swift. thank you.
