### ISSUE TITLE
Calling C functions from Swift

### ISSUE THREAD

**Issue by ianba3** [tinysun212/swift-cygwin#3]
I would like to call some C functions from Swift.  I am trying to use a Bridging-Header.h to accomplish this.  However, when I try to compile:

> ```
> swiftc -c SwiftTest.swift -import-objc-header Bridging-Header.h 
> ```

I get an error:

> ```
> <unknown>:0: error: failed to import bridging header 'Bridging-Header.h'
> ```

SwiftTest.swift contains:
`hello_c("World".cStringUsingEncoding(NSUTF8StringEncoding))`

Bridging-Header.h is empty, just to make sure there's nothing offending in it.

However, Bridging-Header.h previously contained:
`#import "SwiftAPI.h"`

And SwiftAPI.h contains:
`void hello_c(const char * name);`

With a corresponding SwiftAPI.c:

```
    #include "SwiftAPI.h"
    #include <stdio.h>
    void hello_c(const char * name) {
        printf("Hello %s in C\n", name);
    }
```

Is there a better way to do this?
Is there a way to get more detailed error messages?

Thanks a lot!

**Comment by tinysun212** [comment]
With same `SwiftAPI.h` and `SwiftAPI.c` of yours,

```
$ cat SwiftTest.swift
hello_c("World")

$ gcc -c -o SwiftAPI.o SwiftAPI.c

$ swiftc -import-objc-header SwiftAPI.h SwiftTest.swift SwiftAPI.o -o SwiftTest.exe

$ ./SwiftTest
Hello World in C
```

`Bridging-Header.h` is not used.

**Comment by ianba3** [comment]
Thanks for the quick reply, however it did not work for me.  Is there a compiler or library or something (clang.exe?) that swiftc is relying on?  

As per the instructions in README.txt, I'm launching from the VS2015 x64 Native Tools Command Promt (but I also tried this in MSYS with MinGW\bin in the path, with the same results):

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>cd c:\SwiftAPI

c:\SwiftAPI>path=%path%;c:\MinGW\bin

c:\SwiftAPI>type SwiftAPI.h
    void hello_c(const char * name);

c:\SwiftAPI>type SwiftAPI.c
#include "SwiftAPI.h"
#include <stdio.h>
void hello_c(const char * name) {
    printf("Hello %s in C\n", name);
}

c:\SwiftAPI>type SwiftTest.swift
hello_c("World")

c:\SwiftAPI>gcc -c -o SwiftAPI.o SwiftAPI.c

c:\SwiftAPI>swiftc -import-objc-header SwiftAPI.h SwiftTest.swift SwiftAPI.o -o SwiftTest.exe
<unknown>:0: error: failed to import bridging header 'SwiftAPI.h'
```

**Comment by ianba3** [comment]
Thanks a lot.  That worked!
