### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by blasterinblack** [tinysun212/swift-cygwin#8]
Hi,

congratulations for the job done so far!
I wonder about the status this project. I assume it is not being actively developed anymore.
Is there any possibility you could publish a document about the main difficulties you had to go through and the challenges ahead? That would surely help some of us consider taking over further development.

Thanks in advance!

D.

**Comment by tinysun212** [comment]
It seemed that this project is not active. In fact, I actively developed for MinGW port and [wxSwift](https://github.com/tinysun212/wxSwift) pilot.
You can see it in the commit history of the 'upstream-with-windows' branch of this repo, and the master branch of the wxSwift.

I need some time for packing and releasing those build.
You can see the Swift coded sample UI program running on Windows in a few days.

Thanks for interested in this project.

**Comment by blasterinblack** [comment]
Thanks for your quick answer! I will have a look at those. Cheers!

**Comment by Dev1an** [comment]
Cool! Is it the intention to pull this fork back into the original apple/swift repository?

**Comment by tinysun212** [comment]
@blasterinblack Please check  https://github.com/SwiftForWindows/SwiftForWindows/releases/tag/v1.6

@Dev1an Yes, as I submitted multiple pool requests in the past, I will continue to submit PRs. However, it will take time for me to prepare and it will take time for people to review the submitted PR.

**Comment by Scellow** [comment]
Wow, this is impressive work! 

Just tested it and it works like a charm, nice job dude!

**Comment by tinysun212** [comment]
Thanks for your cheering.
Please promote http://SwiftForWindows.github.io to your friends.

**Comment by blasterinblack** [comment]
I will promote it!

Btw, I am also working on yet another project for extending Swift's support for platforms. I will let you know as soon as I have something to show, maybe you will find it interesting.

Congratulations for such a great job!
